
/* Gregory Haynes 
   CSC 451 Section 701
   Assignment 6
   11/14/2016 */



--1--
SELECT NAME, CUSTOMERID 
	FROM CUSTOMER 
	ORDER BY NAME;
	
--2--
SELECT * 
	FROM CUSTOMER 
	WHERE State LIKE '%IL%'
	ORDER BY CUSTOMERID;
	
--3--	
SELECT NAME 
	FROM CUSTOMER 
	WHERE NAME LIKE '%Furniture%';
	
--4--
SELECT NAME, CITY, STATE 
	 FROM CUSTOMER 
	 WHERE STATE LIKE '%CA%' 
	 OR STATE LIKE '%FL%';
	 
--5--	 
SELECT DISTINCT STATE 
	  FROM CUSTOMER 
	  ORDER BY STATE;
	  
	  
--6--
SELECT DESCRIPTION, PRICE, FINISH 
	FROM PRODUCT 
	ORDER BY PRICE DESC, DESCRIPTION;
	
	
--7--
SELECT COUNT(CUSTOMERID), ORDERDATE
	FROM ORDERTABLE 
	GROUP BY ORDERDATE
	ORDER BY ORDERDATE;

	
--8--
SELECT ORDERID, SUM(Quantity)
	FROM ORDERLINE
	GROUP BY ORDERID
	ORDER BY SUM(Quantity) DESC;
	
	
	
--9--
SELECT OrderID, State, CUSTOMER.CustomerID
	FROM (CUSTOMER INNER JOIN ORDERTABLE ON CUSTOMER.CustomerID=ORDERTABLE.CustomerID)
	ORDER BY OrderID;
	
	
--10--
SELECT ORDERLINE.ProductID, SUM(Quantity), COUNT(Description)
	FROM (ORDERLINE INNER JOIN PRODUCT ON ORDERLINE.ProductID=PRODUCT.ProductID)
	GROUP BY ORDERLINE.ProductID
	ORDER BY ProductID;



	